version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/src"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/brick/hooks"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/tool/generator"
    schedule:
      interval: "daily"